name: Lib.so Build

permissions:
  contents: write

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build native lib
        run: ./gradlew assembleDebug

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Auto Lib.so Build ${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload .so files to release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/intermediates/merged_native_libs/debug/out/lib/**/lib*.so
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}